### PR TITLE
Added proto of track DOCA calculation

### PR DESCRIPTION
**Pull request by bcouturi**
This is a first which seems to run but proper validation is still needed.

### CODE REVIEW

**Comment by particleist** [comment]
If I look at track_devdist, it is always either 0 or a huge negative number. This smells wrong, can you have a look please?

**Comment by particleist** [comment]
I am stupid, this is because I am still using a tuple without the D vertex position as an input. Where can I get a new one?

**Comment by bcouturi** [comment]
Hi Vava,

I think it's a bug as the position was actually there (VX, VY, VZ were the end vertex indeed).
Looking into it.

Ben

**Comment by particleist** [comment]
could it be because here

outtree.Branch('track_devdist',arraysforouttree_ddist[0],'track_devdist/F')

you don't say

track_devdist[nTracks]

?

**Pull request merged**
